# Generated by Django 5.0.2 on 2024-02-26 12:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views_alter_board_description_alter_board_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
